### ISSUE TITLE
Whenever you use "fstful" widget, it creates a widget breaking lint library_private_types_in_public_api

### ISSUE THREAD

**Issue by AlvBarros** [Alexisvt/flutter-snippets#14]
Hey there!

Love your extension btw.

I've noticed when you input "fstful" snippet, the generated Widget breaks dart lint library_private_types_in_public_api, as described [here](https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html).

![image](https://user-images.githubusercontent.com/33898913/174492042-118a4052-e299-4519-a098-823ef0cb8546.png)

This is very simple, though, and creates no errors. Just poiting it out!

**Comment by AlvBarros** [comment]
I've created a quick PR with the solution by generating a public State<>, and then using it in createState() return method.
https://github.com/Alexisvt/flutter-snippets/pull/15

This is how the "login.dart" above would look like:

![image](https://user-images.githubusercontent.com/33898913/174492307-e618d44a-36e6-4bbd-b8b9-5bd8e4bd4be5.png)

**Comment by Alexisvt** [comment]
Hey @AlvBarros, thank you for the heads up, yeah, I looked at your change, and it looks good to me; let me merge it and do the necessary steps to publish these changes in the evening!

**Comment by norpan** [comment]
I think you should still keep the actual state private; it should be _LoginState, according to the docs.
https://api.flutter.dev/flutter/widgets/StatefulWidget/createState.html
