### ISSUE TITLE
vscode theme & font

### ISSUE THREAD

**Issue by djkloop** [Alexisvt/flutter-snippets#3]
Can you ask what themes and fonts are used by vscode? Too beautiful...

**Comment by Alexisvt** [comment]
Hello! Yes of course, sorry for the late response, the font is Operator mono and the name of the that theme is [monokai](https://marketplace.visualstudio.com/items?itemName=s3gf4ult.monokai-vibrant), but now I use this one [Shade Of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) which I think it looks better that the other one.
