### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by zyllus17** [Alexisvt/flutter-snippets#8]
I would like to contribute. How can I contribute?
If you can make a GIF or a video on how to add a widget, it would be great.

**Comment by alex3rq** [comment]
This is a good start if you want to know how to contribute.

https://github.com/MarcDiethelm/contributing/blob/master/README.md

**Comment by zyllus17** [comment]
> This is a good start if you want to know how to contribute.
> 
> https://github.com/MarcDiethelm/contributing/blob/master/README.md

I meant to say that I wanted to create and contribute snippets and add to this extension.

**Comment by zyllus17** [comment]
Its been 2 years since the extension received any update, I created my own [extension](https://github.com/zyllus17/flutter-snippets).
